### PR TITLE
Fixed a variable error in the praiseUser method

### PR DESCRIPTION
**Pull request by amsoell**
Also added some awesome new high fives.
high five

### CODE REVIEW

**Comment by Marthyn** [comment]
ah awesome thanks! :D

**Comment by Marthyn** [comment]
I'll make a new release today :)

**Comment by Marthyn** [comment]
@amsoell 0.1.3 is now available with your fixes :dancer:

**Comment by amsoell** [comment]
Thank _you_, this has been a fun script to have on our team :)

**Comment by Marthyn** [comment]
Great! :) Also spread the word then to other devs you know, employees should be praised and high fived more often :smile:

**Pull request merged**
